# Generated by Django 3.0.6 on 2020-06-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='descp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(null=True, upload_to='MyPics'),
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
