# Generated by Django 3.0.6 on 2020-06-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelo', '0002_auto_20200612_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='descp',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(default=True, upload_to='MyPics'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
