# Generated by Django 3.0.6 on 2020-06-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelo', '0003_auto_20200612_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=True),
        ),
    ]
